extra_css:
  - css/extra.css
  
theme:
  name: material
  logo: assets/sclogo.png
  favicon: assets/sclogo_white.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  #font:
    #text: "TTSupermolot-BoldItalic"
    
site_name: Simucube Online Guide

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - abbr
  - pymdownx.snippets:
      auto_append:
        - assets/abbreviations.md
  - pymdownx.keys
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
    - Home: index.md
    - ActivePedal: 
        - Getting started: ActivePedal/Getting started.md
        - Installation:
          - Items needed: ActivePedal/Items needed.md
          - Mounting: ActivePedal/Mounting.md
          - Cabling: ActivePedal/Cabling.md
          - Mechanical adjustments: ActivePedal/Mechanical adjustments.md
          - Software: ActivePedal/Software.md
        - Hazards & safety: ActivePedal/Safety.md
        - Usage: 
          - First time use: ActivePedal/First use.md
          - Profile templates: ActivePedal/Templates.md
          - Travel range: ActivePedal/Travel range.md
          - Force curve: ActivePedal/Force curve.md
          - Effects: ActivePedal/Effects.md
        - FAQ: ActivePedal/FAQ.md
        - Troubleshooting: ActivePedal/Troubleshooting.md
        - Specifications & developers:
          - Specifications: ActivePedal/Specifications.md
          - Game telemetry support: ActivePedal/Telemetry.md
          - Dimensions & 3D models: ActivePedal/3D models.md
          - API: ActivePedal/API.md
    - TrueDrive 2:
        - Getting TrueDrive: TrueDrive/Getting started.md
        - App overview: TrueDrive/Overview.md
        - Profile manager: TrueDrive/Profile manager.md
        - Device settings: 
          - ActivePedal: TrueDrive/ActivePedal device settings.md
          - Passive pedal: TrueDrive/Passive pedal device settings.md
        - Troubleshooting: TrueDrive/Troubleshooting.md
